# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'GLAlertToolDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GLAlertToolDemo
  
  pod 'GLLanguageTool'
  pod 'MBProgressHUD'#, '~> 1.1.0'
  pod 'GLScanner'#, '~> 1.0.1'

end
